import {Router} from "../modules/Router.js";
import {LoginPage} from "../blocks/Login/index.js";
import {SigninPage} from "../blocks/Signin/index.js";
import {ChatPage} from "../blocks/Chat/index.js";
import {ProfilePage} from "../blocks/Profile/index.js";
import {ErrorPage} from "../blocks/Error/index.js";
import {Wrapper} from "../components/Wrapper/index.js";
import {PropsLogin} from "../blocks/Login/login.props.js";
import {PropsSignin} from "../blocks/Signin/signin.props.js";
import {PropsChat} from "../blocks/Chat/chat.props.js";
import {PropsProfile} from "../blocks/Profile/profile.props.js";
import {PropsChangeProfile} from "../blocks/Profile/change_profile.props.js";
import {PropsChangePassword} from "../blocks/Profile/change_password.props.js";
import {PropsChangePhoto} from "../blocks/Profile/change_photo.props.js";
import {PropsAddUser} from "../blocks/Chat/add_user.props.js";
import {PropsRemoveUser} from "../blocks/Chat/remove_user.props.js";
import {PropsAddChat} from "../blocks/Chat/add_chat.props.js";
import {PropsError404} from "../blocks/Error/404.props.js";
import {PropsError500} from "../blocks/Error/500.props.js";
import {ChatController} from "../controllers/ChatController.js";
import {ProfileController} from "../controllers/ProfileController.js";

(() => {
    const router = new Router();
    const rootQuery = {rootQuery: "#root"};

    router.use("/", LoginPage, Object.assign(PropsLogin, rootQuery));
    router.use("/signin", SigninPage, Object.assign(PropsSignin, rootQuery));
    router.use("/chat", ChatPage, Object.assign(PropsChat, rootQuery), ChatController.getChats);
    router.use("/profile", ProfilePage, Object.assign(PropsProfile, rootQuery), ProfileController.getProfile);
    router.use("/change_profile", ProfilePage, Object.assign(PropsChangeProfile, rootQuery), ProfileController.getProfile);
    router.use("/change_password", ProfilePage, Object.assign(PropsChangePassword, rootQuery), ProfileController.getProfile);
    router.use("/change_photo", Wrapper, Object.assign(PropsChangePhoto, rootQuery), ProfileController.getProfile);
    router.use("/add_user", Wrapper, Object.assign(PropsAddUser, rootQuery), ChatController.getChats);
    router.use("/remove_user", Wrapper, Object.assign(PropsRemoveUser, rootQuery), ChatController.getChats);
    router.use("/add_chat", Wrapper, Object.assign(PropsAddChat, rootQuery), ChatController.getChats);
    router.use("/404", ErrorPage, Object.assign(PropsError404, rootQuery));
    router.use("/500", ErrorPage, Object.assign(PropsError500, rootQuery));
    router.start();
})();